# Generated by Django 5.1.5 on 2025-02-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'agents'), (2, 'hotel_vendors'), (3, 'customer')], default=3),
        ),
    ]
