# Generated by Django 5.1.5 on 2025-02-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='youtube_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/images/')),
                ('image_type', models.CharField(choices=[('banner', 'Banner'), ('featured', 'Featured'), ('gallery', 'Gallery')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='hotels.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='banner_images',
            field=models.ManyToManyField(blank=True, related_name='banner_images', to='hotels.hotelimage'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='featured_images',
            field=models.ManyToManyField(blank=True, related_name='featured_images', to='hotels.hotelimage'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='hotel_gallery', to='hotels.hotelimage'),
        ),
        migrations.CreateModel(
            name='HotelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('content', models.TextField(null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_policies', to='hotels.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='policies',
            field=models.ManyToManyField(blank=True, related_name='hotel_policies', to='hotels.hotelpolicy'),
        ),
        migrations.CreateModel(
            name='HotelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enable_extra_price', models.BooleanField(default=False)),
                ('enable_service_fee', models.BooleanField(default=False)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('minimum_advance_reservations', models.IntegerField()),
                ('minimum_day_stay_requirements', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_details', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.BooleanField(default=False)),
                ('boat', models.BooleanField(default=False)),
                ('holiday_home', models.BooleanField(default=False)),
                ('villa', models.BooleanField(default=False)),
                ('cabin', models.BooleanField(default=False)),
                ('hostel', models.BooleanField(default=False)),
                ('lodge', models.BooleanField(default=False)),
                ('mansion', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('bar', models.BooleanField(default=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('conference_room', models.BooleanField(default=False)),
                ('room_service', models.BooleanField(default=False)),
                ('cleaning_service', models.BooleanField(default=False)),
                ('laundry_service', models.BooleanField(default=False)),
                ('shuttle_service', models.BooleanField(default=False)),
                ('concierge_service', models.BooleanField(default=False)),
                ('hour24_reception', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotels.hotel')),
            ],
        ),
    ]
