# Generated by Django 5.1.5 on 2025-02-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_hotel_rating_hotel_youtube_video_hotelimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelpricing',
            name='enable_extra_price',
        ),
        migrations.RemoveField(
            model_name='hotelpricing',
            name='enable_service_fee',
        ),
    ]
