# Generated by Django 5.1.5 on 2025-02-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_hotelpricing_enable_extra_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservices',
            name='banquet',
            field=models.BooleanField(default=False),
        ),
    ]
